				<div class="copyright full-width">

                     <div class="container">

                         <div class="copyright-right">                

                            © Copyright 2017<span> Krystal</span>. All Rights Reserved.

                        </div>

                        <div class="pay-men">

                            <a href="#"><img src="img/home1/pay1.jpg" alt="pay1"></a>

                            <a href="#"><img src="img/home1/pay2.jpg" alt="pay2"></a>

                            <a href="#"><img src="img/home1/pay3.jpg" alt="pay3"></a>

                            <a href="#"><img src="img/home1/pay4.jpg" alt="pay4"></a>

                        </div>

                     </div>

                </div>