			<!-- Modal Start -->
			  <div class="modal fade" id="forgetpassword" role="dialog">
				<div class="modal-dialog modal-sm">
				
				  <!-- Modal content-->
				  <div class="modal-content">
					<div class="modal-header">
					  <button type="button" class="close" data-dismiss="modal">&times;</button>
					  <h4 class="modal-title">Reset your password</h4>
					</div>
					<div class="modal-body">
					  <form action="" method="post">
					            <p class="form-row form-row-wide col-md-6 padding-right">

                                    <label>Plese Enter your E-mail:<span class="required">*</span></label>

                                    <input type="password" name="password" class="input-text">

                                </p>
					  </form>
					</div>
					<div class="modal-footer">
					  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					</div>
				  </div>
				  
				</div>
			  </div>
			  <!-- Modal End -->