<div class="footer-top full-width">

                    <div class="container">

                        <div class="row">

                            <div class="col-md-6">

                                <div class="newsletter-title">

                                    <h3 class="h3-newsletter">Sign up to Newsletter</h3>

                                    <span class="span-newsletter">Recevie $50 Coupon for fist Shopping.</span>

                                </div>

                            </div>

                            <div class="col-md-6">

                                <div class="newsletter-form">

                                    <form id="newsletter-validate-detail" class="form subscribe">

                                        <div class="control">

                                            <input type="email" placeholder="Enter your email address" id="newsletter" name="email" class="input-subscribe">

                                            <button type="submit" title="Subscribe" class="btn subscribe">

                                                <span>Sign Up</span>

                                            </button>

                                        </div>

                                    </form>

                                </div>

                            </div>

                        </div>

                    </div>

                </div>
