
        <!-- MAIN -->

        <main class="site-main">

            <div class="block-slide">

                <div class="main-slide full-width slide-opt-4">

                    <div class="owl-carousel nav-style5" data-nav="true" data-autoplay="false" data-dots="true" data-loop="true" data-margin="0" data-responsive='{"0":{"items":1},"600":{"items":1},"1000":{"items":1}}'>

                        <div class="item-slide item-slide-1">

                            <div class="container">

                                <div class="slide-desc slide-desc-1">

                                    <div class="p-primary">Great Range of <span>Exclusive Furniture</span> Chair.</div>

                                    <p>Exclusive furniture packages to suit every need.start freom as little as <span class="color-red">$300.00</span></p>

                                    <a href="#" class="btn-shop-now">Shop Now</a>                            

                                </div>

                            </div>

                        </div>

                        <div class="item-slide item-slide-2">

                            <div class="container">

                                <div class="slide-desc slide-desc-2">

                                    <p class="p-second">How to work a</p>

                                    <div class="p-primary">Sectional sofa</div>

                                    <p class="p-second">into your space</p>

                                    <a href="#" class="btn-shop-now">Shop Now</a>                            

                                </div>

                            </div>

                        </div>

                        <div class="item-slide item-slide-3">

                            <div class="container">

                                <div class="slide-desc slide-desc-3">

                                    <p class="p-second">Great Range</p>

                                    <div class="p-primary">Of Exclusive Furniture Packages</div>

                                    <p>Exclusive furniture packages to suit every need.</p>

                                    <a href="#" class="btn-shop-now">Shop Now</a>                            

                                </div>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

            <div class="block-promotion-banner">

                <div class="container">

                    <div class="row">

                        <div class="col-sm-6 col-xs-6">

                            <div class="promotion-banner style-6">

                                <a href="#" class="banner-img"><img src="img/home4/banner1.jpg" alt="banner1"></a>

                            </div>

                        </div>

                        <div class="col-sm-6 col-xs-6">

                            <div class="promotion-banner style-6">

                                <a href="#" class="banner-img"><img src="img/home4/banner2.jpg" alt="banner2"></a>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

            <div class="block-feature-product">

                <div class="container">

                    <div class="title-of-section">Featured Products</div>

                    <div class="tab-product tab-product-fade-effect">

                        <ul class="box-tabs nav-tab">

                            <li class="active"><a data-animated="" data-toggle="tab" href="#tab-1">All Products </a></li>

                            <li><a data-animated="fadeInLeft" data-toggle="tab" href="#tab-2">Furniture</a></li>

                            <li><a data-animated="fadeInDownBig" data-toggle="tab" href="#tab-1">Wooden Chairs</a></li>

                            <li><a data-animated="zoomInUp" data-toggle="tab" href="#tab-2">Sofa</a></li>

                        </ul>

                        <div class="tab-content">

                            <div class="tab-container">

                                <div id="tab-1" class="tab-panel active">

                                    <div class="owl-carousel nav-style2 border-background equal-container" data-nav="true" data-autoplay="false" data-dots="false" data-loop="true" data-margin="0" data-responsive='{"0":{"items":1},"480":{"items":2},"600":{"items":3},"1000":{"items":5}}'>

                                        <div class="product-item style1">

                                            <div class="product-inner equal-elem">

                                                <div class="product-thumb">

                                                    <div class="thumb-inner">

                                                        <a href="#"><img src="img/home4/p1.jpg" alt="p1"></a>

                                                    </div>

                                                    <a href="#" class="quick-view">Quick View</a>

                                                </div>

                                                <div class="product-innfo">

                                                    <div class="product-name"><a href="#">Fleece-lined anorak</a></div>

                                                    <span class="price price-dark">

                                                        <ins>$229.00</ins>

                                                    </span>

                                                    <span class="star-rating">

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <span class="review">5 Review(s)</span>

                                                    </span>

                                                    <div class="group-btn-hover">

                                                        <div class="inner">

                                                            <a href="#" class="compare"><i class="flaticon-refresh-square-arrows"></i></a>

                                                            <a href="#" class="add-to-cart">Add to cart</a>

                                                            <a href="#" class="wishlist"><i class="fa fa-heart-o" aria-hidden="true"></i></a>

                                                        </div>

                                                    </div>

                                                </div>

                                            </div>

                                        </div>

                                        <div class="product-item style1">

                                            <div class="product-inner equal-elem">

                                                <div class="product-thumb">

                                                    <div class="thumb-inner">

                                                        <a href="#"><img src="img/home4/p2.jpg" alt="p2"></a>

                                                    </div>

                                                     <span class="onnew">New</span>

                                                     <a href="#" class="quick-view">Quick View</a>

                                                </div>

                                                <div class="product-innfo">

                                                    <div class="product-name"><a href="#">Chanel Volcanic Dining Chair</a></div>

                                                    <span class="price price-dark">

                                                        <ins>$229.00</ins>

                                                    </span>

                                                    <span class="star-rating">

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <span class="review">5 Review(s)</span>

                                                    </span>

                                                    <div class="group-btn-hover">

                                                        <div class="inner">

                                                            <a href="#" class="compare"><i class="flaticon-refresh-square-arrows"></i></a>

                                                            <a href="#" class="add-to-cart">Add to cart</a>

                                                            <a href="#" class="wishlist"><i class="fa fa-heart-o" aria-hidden="true"></i></a>

                                                        </div>

                                                    </div>

                                                </div>

                                            </div>

                                        </div>

                                        <div class="product-item style1">

                                            <div class="product-inner equal-elem">

                                                <div class="product-thumb">

                                                    <div class="thumb-inner">

                                                        <a href="#"><img src="img/home4/p3.jpg" alt="p3"></a>

                                                    </div>

                                                     <span class="onsale">-50%</span>

                                                     <a href="#" class="quick-view">Quick View</a>

                                                </div>

                                                <div class="product-innfo">

                                                    <div class="product-name"><a href="#">Zola Licorice Dining Chair</a></div>

                                                    <span class="price">

                                                        <ins>$229.00</ins>

                                                        <del>$259.00</del>

                                                    </span>

                                                    <span class="star-rating">

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <span class="review">5 Review(s)</span>

                                                    </span>

                                                    <div class="group-btn-hover">

                                                        <div class="inner">

                                                            <a href="#" class="compare"><i class="flaticon-refresh-square-arrows"></i></a>

                                                            <a href="#" class="add-to-cart">Add to cart</a>

                                                            <a href="#" class="wishlist"><i class="fa fa-heart-o" aria-hidden="true"></i></a>

                                                        </div>

                                                    </div>

                                                </div>

                                            </div>

                                        </div>

                                        <div class="product-item style1">

                                            <div class="product-inner equal-elem">

                                                <div class="product-thumb">

                                                    <div class="thumb-inner">

                                                        <a href="#"><img src="img/home4/p4.jpg" alt="p4"></a>

                                                    </div>

                                                    <a href="#" class="quick-view">Quick View</a>

                                                </div>

                                                <div class="product-innfo">

                                                    <div class="product-name"><a href="#">Broadway Slipcover Chair</a></div>

                                                    <span class="price price-dark">

                                                        <ins>$229.00</ins>

                                                    </span>

                                                    <div class="group-btn-hover">

                                                        <div class="inner">

                                                            <a href="#" class="compare"><i class="flaticon-refresh-square-arrows"></i></a>

                                                            <a href="#" class="add-to-cart">Add to cart</a>

                                                            <a href="#" class="wishlist"><i class="fa fa-heart-o" aria-hidden="true"></i></a>

                                                        </div>

                                                    </div>

                                                </div>

                                            </div>

                                        </div>

                                        <div class="product-item style1">

                                            <div class="product-inner equal-elem">

                                                <div class="product-thumb">

                                                    <div class="thumb-inner">

                                                        <a href="#"><img src="img/home4/p5.jpg" alt="p5"></a>

                                                    </div>

                                                    <span class="onsale">-50%</span>

                                                    <a href="#" class="quick-view">Quick View</a>

                                                </div>

                                                <div class="product-innfo">

                                                    <div class="product-name"><a href="#">Chanel Volcanic Dining Chair</a></div>

                                                    <span class="price">

                                                        <ins>$229.00</ins>

                                                        <del>$259.00</del>

                                                    </span>

                                                    <span class="star-rating">

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <span class="review">5 Review(s)</span>

                                                    </span>

                                                    <div class="group-btn-hover">

                                                        <div class="inner">

                                                            <a href="#" class="compare"><i class="flaticon-refresh-square-arrows"></i></a>

                                                            <a href="#" class="add-to-cart">Add to cart</a>

                                                            <a href="#" class="wishlist"><i class="fa fa-heart-o" aria-hidden="true"></i></a>

                                                        </div>

                                                    </div>

                                                </div>

                                            </div>

                                        </div>

                                    </div>

                                </div>

                                <div id="tab-2" class="tab-panel">

                                    <div class="owl-carousel nav-style2 border-background equal-container" data-nav="true" data-autoplay="false" data-dots="false" data-loop="true" data-margin="0" data-responsive='{"0":{"items":1},"480":{"items":2},"600":{"items":3},"1000":{"items":5}}'>

                                        <div class="product-item style1">

                                            <div class="product-inner equal-elem">

                                                <div class="product-thumb">

                                                    <div class="thumb-inner">

                                                        <a href="#"><img src="img/home4/p1.jpg" alt="p1"></a>

                                                    </div>

                                                    <a href="#" class="quick-view">Quick View</a>

                                                </div>

                                                <div class="product-innfo">

                                                    <div class="product-name"><a href="#">Fleece-lined anorak</a></div>

                                                    <span class="price price-dark">

                                                        <ins>$229.00</ins>

                                                    </span>

                                                    <span class="star-rating">

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <span class="review">5 Review(s)</span>

                                                    </span>

                                                    <div class="group-btn-hover">

                                                        <div class="inner">

                                                            <a href="#" class="compare"><i class="flaticon-refresh-square-arrows"></i></a>

                                                            <a href="#" class="add-to-cart">Add to cart</a>

                                                            <a href="#" class="wishlist"><i class="fa fa-heart-o" aria-hidden="true"></i></a>

                                                        </div>

                                                    </div>

                                                </div>

                                            </div>

                                        </div>

                                        <div class="product-item style1">

                                            <div class="product-inner equal-elem">

                                                <div class="product-thumb">

                                                    <div class="thumb-inner">

                                                        <a href="#"><img src="img/home4/p2.jpg" alt="p2"></a>

                                                    </div>

                                                     <span class="onnew">New</span>

                                                     <a href="#" class="quick-view">Quick View</a>

                                                </div>

                                                <div class="product-innfo">

                                                    <div class="product-name"><a href="#">Chanel Volcanic Dining Chair</a></div>

                                                    <span class="price price-dark">

                                                        <ins>$229.00</ins>

                                                    </span>

                                                    <span class="star-rating">

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <span class="review">5 Review(s)</span>

                                                    </span>

                                                    <div class="group-btn-hover">

                                                        <div class="inner">

                                                            <a href="#" class="compare"><i class="flaticon-refresh-square-arrows"></i></a>

                                                            <a href="#" class="add-to-cart">Add to cart</a>

                                                            <a href="#" class="wishlist"><i class="fa fa-heart-o" aria-hidden="true"></i></a>

                                                        </div>

                                                    </div>

                                                </div>

                                            </div>

                                        </div>

                                        <div class="product-item style1">

                                            <div class="product-inner equal-elem">

                                                <div class="product-thumb">

                                                    <div class="thumb-inner">

                                                        <a href="#"><img src="img/home4/p3.jpg" alt="p3"></a>

                                                    </div>

                                                     <span class="onsale">-50%</span>

                                                     <a href="#" class="quick-view">Quick View</a>

                                                </div>

                                                <div class="product-innfo">

                                                    <div class="product-name"><a href="#">Zola Licorice Dining Chair</a></div>

                                                    <span class="price">

                                                        <ins>$229.00</ins>

                                                        <del>$259.00</del>

                                                    </span>

                                                    <span class="star-rating">

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <span class="review">5 Review(s)</span>

                                                    </span>

                                                    <div class="group-btn-hover">

                                                        <div class="inner">

                                                            <a href="#" class="compare"><i class="flaticon-refresh-square-arrows"></i></a>

                                                            <a href="#" class="add-to-cart">Add to cart</a>

                                                            <a href="#" class="wishlist"><i class="fa fa-heart-o" aria-hidden="true"></i></a>

                                                        </div>

                                                    </div>

                                                </div>

                                            </div>

                                        </div>

                                        <div class="product-item style1">

                                            <div class="product-inner equal-elem">

                                                <div class="product-thumb">

                                                    <div class="thumb-inner">

                                                        <a href="#"><img src="img/home4/p4.jpg" alt="p4"></a>

                                                    </div>

                                                    <a href="#" class="quick-view">Quick View</a>

                                                </div>

                                                <div class="product-innfo">

                                                    <div class="product-name"><a href="#">Broadway Slipcover Chair</a></div>

                                                    <span class="price price-dark">

                                                        <ins>$229.00</ins>

                                                    </span>

                                                    <div class="group-btn-hover">

                                                        <div class="inner">

                                                            <a href="#" class="compare"><i class="flaticon-refresh-square-arrows"></i></a>

                                                            <a href="#" class="add-to-cart">Add to cart</a>

                                                            <a href="#" class="wishlist"><i class="fa fa-heart-o" aria-hidden="true"></i></a>

                                                        </div>

                                                    </div>

                                                </div>

                                            </div>

                                        </div>

                                        <div class="product-item style1">

                                            <div class="product-inner equal-elem">

                                                <div class="product-thumb">

                                                    <div class="thumb-inner">

                                                        <a href="#"><img src="img/home4/p5.jpg" alt="p5"></a>

                                                    </div>

                                                    <span class="onsale">-50%</span>

                                                    <a href="#" class="quick-view">Quick View</a>

                                                </div>

                                                <div class="product-innfo">

                                                    <div class="product-name"><a href="#">Chanel Volcanic Dining Chair</a></div>

                                                    <span class="price">

                                                        <ins>$229.00</ins>

                                                        <del>$259.00</del>

                                                    </span>

                                                    <span class="star-rating">

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <i class="fa fa-star" aria-hidden="true"></i>

                                                        <span class="review">5 Review(s)</span>

                                                    </span>

                                                    <div class="group-btn-hover">

                                                        <div class="inner">

                                                            <a href="#" class="compare"><i class="flaticon-refresh-square-arrows"></i></a>

                                                            <a href="#" class="add-to-cart">Add to cart</a>

                                                            <a href="#" class="wishlist"><i class="fa fa-heart-o" aria-hidden="true"></i></a>

                                                        </div>

                                                    </div>

                                                </div>

                                            </div>

                                        </div>

                                    </div>

                                </div>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

            <div class="block-sale-product style2 full-width block-background">

                <div class="container">

                    <div class="title-of-section">Home Furnitures</div>

                    <div class="owl-carousel nav-style2 border-background equal-container" data-nav="true" data-autoplay="false" data-dots="false" data-loop="true" data-margin="0" data-responsive='{"0":{"items":1},"480":{"items":2},"600":{"items":3},"1000":{"items":3}}'>

                        <div class="product-item style1">

                            <div class="product-inner equal-elem">

                                <div class="product-thumb">

                                    <div class="thumb-inner">

                                        <a href="#"><img src="img/home4/h1.jpg" alt="h1"></a>

                                    </div>

                                    <span class="onsale">-50%</span>

                                    <a href="#" class="quick-view">Quick View</a>

                                </div>

                                <div class="product-innfo">

                                    <div class="product-name"><a href="#">Coral Springs Arm Chair</a></div>

                                    <span class="price">

                                        <ins>$229.00</ins>

                                        <del>$259.00</del>

                                    </span>

                                    <span class="star-rating">

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <span class="review">5 Review(s)</span>

                                    </span>

                                    <div class="group-btn-hover style2">

                                        <a href="#" class="add-to-cart"><i class="fa fa-shopping-bag" aria-hidden="true"></i></a>

                                        <a href="#" class="compare"><i class="flaticon-refresh-square-arrows"></i></a>

                                        <a href="#" class="wishlist"><i class="fa fa-heart-o" aria-hidden="true"></i></a>

                                    </div>

                                </div>

                            </div>

                        </div>

                        <div class="product-item style1">

                            <div class="product-inner equal-elem">

                                <div class="product-thumb">

                                    <div class="thumb-inner">

                                        <a href="#"><img src="img/home4/h2.jpg" alt="h2"></a>

                                    </div>

                                    <span class="onnew">new</span>

                                    <a href="#" class="quick-view">Quick View</a>

                                </div>

                                <div class="product-innfo"> 

                                    <div class="product-name"><a href="#">Alai Smok Side Chair</a></div>

                                    <span class="price price-dark">

                                        <ins>$229.00</ins>

                                    </span>

                                    <div class="group-btn-hover style2">

                                        <a href="#" class="add-to-cart"><i class="fa fa-shopping-bag" aria-hidden="true"></i></a>

                                        <a href="#" class="compare"><i class="flaticon-refresh-square-arrows"></i></a>

                                        <a href="#" class="wishlist"><i class="fa fa-heart-o" aria-hidden="true"></i></a>

                                    </div>

                                </div>

                            </div>

                        </div>

                        <div class="product-item style1">

                            <div class="product-inner equal-elem">

                                <div class="product-thumb">

                                    <div class="thumb-inner">

                                        <a href="#"><img src="img/home4/h3.jpg" alt="h3"></a>

                                    </div>

                                    <span class="onsale">-50%</span>

                                    <a href="#" class="quick-view">Quick View</a>

                                </div>

                                <div class="product-innfo">

                                    <div class="product-name"><a href="#">Lawn Deck Foldable Adirondack Wood Chai</a></div>

                                    <span class="price">

                                        <ins>$229.00</ins>

                                        <del>$259.00</del>

                                    </span>

                                    <span class="star-rating">

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <span class="review">5 Review(s)</span>

                                    </span>

                                    <div class="group-btn-hover style2">

                                        <a href="#" class="add-to-cart"><i class="fa fa-shopping-bag" aria-hidden="true"></i></a>

                                        <a href="#" class="compare"><i class="flaticon-refresh-square-arrows"></i></a>

                                        <a href="#" class="wishlist"><i class="fa fa-heart-o" aria-hidden="true"></i></a>

                                    </div>

                                </div>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

            <div class="block-bestseller-product">

                <div class="container">

                    <div class="title-of-section style2">BestSeller Products</div>

                    <div class="tab-product tab-product-fade-effect">

                        <ul class="box-tabs nav-tab style2">

                            <li class="active"><a data-animated="" data-toggle="tab" href="#tab-3">All Products </a></li>

                            <li><a data-animated="fadeInLeft" data-toggle="tab" href="#tab-4">Furniture</a></li>

                            <li><a data-animated="zoomInUp" data-toggle="tab" href="#tab-3">Wooden Chairs</a></li>

                            <li><a data-animated="zoomInUp" data-toggle="tab" href="#tab-4">Sofa</a></li>

                        </ul>

                        <div class="tab-content">

                            <div class="tab-container">

                                <div id="tab-3" class="tab-panel active">

                                    <div class="owl-carousel equal-container" data-nav="false" data-autoplay="false" data-dots="false" data-loop="true" data-margin="30" data-responsive='{"0":{"items":1},"480":{"items":2},"992":{"items":3}}'>
                                        <div class="owl-one-row">

                                            <div class="product-item style2">

                                                <div class="product-inner equal-elem">

                                                    <div class="product-thumb style1">

                                                        <div class="thumb-inner">

                                                            <a href="#"><img src="img/home4/b1.jpg" alt="b1"></a>

                                                        </div>

                                                    </div>

                                                    <div class="product-innfo">

                                                        <div class="product-name"><a href="#">Marchella Antique Ivory Round Dining Table</a></div>

                                                        <span class="price">

                                                            <ins>$229.00</ins>

                                                            <del>$259.00</del>

                                                            <span class="onsale">-50%</span>

                                                        </span>

                                                        <span class="star-rating">

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <span class="review">5 Review(s)</span>

                                                        </span>

                                                        <a href="#" class="btn-add-to-cart">Add to cart</a>

                                                    </div>

                                                </div>
                                            </div>
                                            <div class="product-item style2">

                                                <div class="product-inner equal-elem">

                                                    <div class="product-thumb style1">

                                                        <div class="thumb-inner">

                                                            <a href="#"><img src="img/home4/b4.jpg" alt="b4"></a>

                                                        </div>

                                                    </div>

                                                    <div class="product-innfo">

                                                        <div class="product-name"><a href="#">Broadway Slipcover Chair</a></div>

                                                        <span class="price">

                                                            <ins>$229.00</ins>

                                                            <del>$259.00</del>

                                                            <span class="onnew">new</span>

                                                        </span>

                                                        <span class="star-rating">

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <span class="review">5 Review(s)</span>

                                                        </span>

                                                        <a href="#" class="btn-add-to-cart">Add to cart</a>

                                                    </div>

                                                </div>
                                            </div>

                                        </div>
                                        <div class="owl-one-row">

                                            <div class="product-item style2">

                                                <div class="product-inner equal-elem">

                                                    <div class="product-thumb style1">

                                                        <div class="thumb-inner">

                                                            <a href="#"><img src="img/home4/b2.jpg" alt="b2"></a>

                                                        </div>

                                                    </div>

                                                    <div class="product-innfo">

                                                        <div class="product-name"><a href="#">Lawn Deck Foldable Adirondack Wood Chai</a></div>

                                                        <span class="price">

                                                            <ins>$229.00</ins>

                                                            <del>$259.00</del>

                                                            <span class="onnew">new</span>

                                                        </span>

                                                        <span class="star-rating">

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <span class="review">5 Review(s)</span>

                                                        </span>

                                                        <a href="#" class="btn-add-to-cart">Add to cart</a>

                                                    </div>

                                                </div>
                                            </div>
                                            <div class="product-item style2">

                                                <div class="product-inner equal-elem">

                                                    <div class="product-thumb style1">

                                                        <div class="thumb-inner">

                                                            <a href="#"><img src="img/home4/b5.jpg" alt="b5"></a>

                                                        </div>

                                                    </div>

                                                    <div class="product-innfo">

                                                        <div class="product-name"><a href="#">Zola Licorice Dining Chair</a></div>

                                                        <span class="price">

                                                            <ins>$229.00</ins>

                                                            <del>$259.00</del>

                                                        </span>

                                                        <span class="star-rating">

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <span class="review">5 Review(s)</span>

                                                        </span>

                                                        <a href="#" class="btn-add-to-cart">Add to cart</a>

                                                    </div>

                                                </div>

                                            </div>
                                        </div>

                                        <div class="owl-one-row">

                                            <div class="product-item style2">

                                                <div class="product-inner equal-elem">

                                                    <div class="product-thumb style1">

                                                        <div class="thumb-inner">

                                                            <a href="#"><img src="img/home4/b3.jpg" alt="b3"></a>

                                                        </div>

                                                    </div>

                                                    <div class="product-innfo">

                                                        <div class="product-name"><a href="#">Coral Springs Arm Chair</a></div>

                                                        <span class="price">

                                                            <ins>$229.00</ins>

                                                            <del>$259.00</del>

                                                        </span>

                                                        <span class="star-rating">

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <span class="review">5 Review(s)</span>

                                                        </span>

                                                        <a href="#" class="btn-add-to-cart">Add to cart</a>

                                                    </div>

                                                </div>
                                            </div>

                                            <div class="product-item style2">

                                                <div class="product-inner equal-elem">

                                                    <div class="product-thumb style1">

                                                        <div class="thumb-inner">

                                                            <a href="#"><img src="img/home4/b6.jpg" alt="b6"></a>

                                                        </div>

                                                    </div>

                                                    <div class="product-innfo">

                                                        <div class="product-name"><a href="#">Chanel Volcanic Dining Chair</a></div>

                                                        <span class="price">

                                                            <ins>$229.00</ins>

                                                            <del>$259.00</del>

                                                            <span class="onsale">-50%</span>

                                                        </span>

                                                        <span class="star-rating">

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <span class="review">5 Review(s)</span>

                                                        </span>

                                                        <a href="#" class="btn-add-to-cart">Add to cart</a>

                                                    </div>

                                                </div>

                                            </div>

                                        </div>

                                    </div>

                                </div>

                                <div id="tab-4" class="tab-panel">

                                    <div class="owl-carousel equal-container" data-nav="false" data-autoplay="false" data-dots="false" data-loop="true" data-margin="30" data-responsive='{"0":{"items":1},"480":{"items":2},"992":{"items":3}}'>
                                        <div class="owl-one-row">

                                            <div class="product-item style2">

                                                <div class="product-inner equal-elem">

                                                    <div class="product-thumb style1">

                                                        <div class="thumb-inner">

                                                            <a href="#"><img src="img/home4/b1.jpg" alt="b1"></a>

                                                        </div>

                                                    </div>

                                                    <div class="product-innfo">

                                                        <div class="product-name"><a href="#">Marchella Antique Ivory Round Dining Table</a></div>

                                                        <span class="price">

                                                            <ins>$229.00</ins>

                                                            <del>$259.00</del>

                                                            <span class="onsale">-50%</span>

                                                        </span>

                                                        <span class="star-rating">

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <span class="review">5 Review(s)</span>

                                                        </span>

                                                        <a href="#" class="btn-add-to-cart">Add to cart</a>

                                                    </div>

                                                </div>
                                            </div>
                                            <div class="product-item style2">

                                                <div class="product-inner equal-elem">

                                                    <div class="product-thumb style1">

                                                        <div class="thumb-inner">

                                                            <a href="#"><img src="img/home4/b4.jpg" alt="b4"></a>

                                                        </div>

                                                    </div>

                                                    <div class="product-innfo">

                                                        <div class="product-name"><a href="#">Broadway Slipcover Chair</a></div>

                                                        <span class="price">

                                                            <ins>$229.00</ins>

                                                            <del>$259.00</del>

                                                            <span class="onnew">new</span>

                                                        </span>

                                                        <span class="star-rating">

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <span class="review">5 Review(s)</span>

                                                        </span>

                                                        <a href="#" class="btn-add-to-cart">Add to cart</a>

                                                    </div>

                                                </div>
                                            </div>

                                        </div>
                                        <div class="owl-one-row">

                                            <div class="product-item style2">

                                                <div class="product-inner equal-elem">

                                                    <div class="product-thumb style1">

                                                        <div class="thumb-inner">

                                                            <a href="#"><img src="img/home4/b2.jpg" alt="b2"></a>

                                                        </div>

                                                    </div>

                                                    <div class="product-innfo">

                                                        <div class="product-name"><a href="#">Lawn Deck Foldable Adirondack Wood Chai</a></div>

                                                        <span class="price">

                                                            <ins>$229.00</ins>

                                                            <del>$259.00</del>

                                                            <span class="onnew">new</span>

                                                        </span>

                                                        <span class="star-rating">

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <span class="review">5 Review(s)</span>

                                                        </span>

                                                        <a href="#" class="btn-add-to-cart">Add to cart</a>

                                                    </div>

                                                </div>
                                            </div>
                                            <div class="product-item style2">

                                                <div class="product-inner equal-elem">

                                                    <div class="product-thumb style1">

                                                        <div class="thumb-inner">

                                                            <a href="#"><img src="img/home4/b5.jpg" alt="b5"></a>

                                                        </div>

                                                    </div>

                                                    <div class="product-innfo">

                                                        <div class="product-name"><a href="#">Zola Licorice Dining Chair</a></div>

                                                        <span class="price">

                                                            <ins>$229.00</ins>

                                                            <del>$259.00</del>

                                                        </span>

                                                        <span class="star-rating">

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <span class="review">5 Review(s)</span>

                                                        </span>

                                                        <a href="#" class="btn-add-to-cart">Add to cart</a>

                                                    </div>

                                                </div>

                                            </div>
                                        </div>

                                        <div class="owl-one-row">

                                            <div class="product-item style2">

                                                <div class="product-inner equal-elem">

                                                    <div class="product-thumb style1">

                                                        <div class="thumb-inner">

                                                            <a href="#"><img src="img/home4/b3.jpg" alt="b3"></a>

                                                        </div>

                                                    </div>

                                                    <div class="product-innfo">

                                                        <div class="product-name"><a href="#">Coral Springs Arm Chair</a></div>

                                                        <span class="price">

                                                            <ins>$229.00</ins>

                                                            <del>$259.00</del>

                                                        </span>

                                                        <span class="star-rating">

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <span class="review">5 Review(s)</span>

                                                        </span>

                                                        <a href="#" class="btn-add-to-cart">Add to cart</a>

                                                    </div>

                                                </div>
                                            </div>

                                            <div class="product-item style2">

                                                <div class="product-inner equal-elem">

                                                    <div class="product-thumb style1">

                                                        <div class="thumb-inner">

                                                            <a href="#"><img src="img/home4/b6.jpg" alt="b6"></a>

                                                        </div>

                                                    </div>

                                                    <div class="product-innfo">

                                                        <div class="product-name"><a href="#">Chanel Volcanic Dining Chair</a></div>

                                                        <span class="price">

                                                            <ins>$229.00</ins>

                                                            <del>$259.00</del>

                                                            <span class="onsale">-50%</span>

                                                        </span>

                                                        <span class="star-rating">

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <i class="fa fa-star" aria-hidden="true"></i>

                                                            <span class="review">5 Review(s)</span>

                                                        </span>

                                                        <a href="#" class="btn-add-to-cart">Add to cart</a>

                                                    </div>

                                                </div>

                                            </div>

                                        </div>

                                    </div>

                                </div>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

            <div class="block-section-brand">
                <div class="container">
                    <div class="section-brand style1">
                        <div class="owl-carousel nav-style3" data-nav="true" data-autoplay="false" data-dots="false" data-loop="true" data-margin="2" data-responsive='{"0":{"items":1},"480":{"items":2},"600":{"items":4},"1000":{"items":6}}'>
                            <a href="#" class="item-brand"><img src="img/home1/brand1.jpg" alt="brand1"></a>
                            <a href="#" class="item-brand"><img src="img/home1/brand1.jpg" alt="brand1"></a>
                            <a href="#" class="item-brand"><img src="img/home1/brand1.jpg" alt="brand1"></a>
                            <a href="#" class="item-brand"><img src="img/home1/brand1.jpg" alt="brand1"></a>
                            <a href="#" class="item-brand"><img src="img/home1/brand1.jpg" alt="brand1"></a>
                            <a href="#" class="item-brand"><img src="img/home1/brand1.jpg" alt="brand1"></a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="block-recent-view">

                <div class="container">

                    <div class="title-of-section">Recently Viewed Products</div>

                    <div class="owl-carousel nav-style2 border-background equal-container" data-nav="true" data-autoplay="false" data-dots="false" data-loop="true" data-margin="0" data-responsive='{"0":{"items":1},"480":{"items":2},"600":{"items":3},"1000":{"items":6}}'>

                        <div class="product-item style1">

                            <div class="product-inner equal-elem">

                                <div class="product-thumb">

                                    <div class="thumb-inner">

                                        <a href="#"><img src="img/home4/r1.jpg" alt="r1"></a>

                                    </div>

                                    <span class="onsale">-50%</span>

                                    <a href="#" class="quick-view">Quick View</a>

                                </div>

                                <div class="product-innfo">

                                    <div class="product-name"><a href="#">Lawn Deck Foldable Adirondack Wood Chai</a></div>

                                    <span class="price">

                                        <ins>$229.00</ins>

                                        <del>$259.00</del>

                                    </span>

                                    <span class="star-rating">

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <span class="review">5 Review(s)</span>

                                    </span>

                                    <div class="group-btn-hover style2">

                                        <a href="#" class="add-to-cart"><i class="fa fa-shopping-bag" aria-hidden="true"></i></a>

                                        <a href="#" class="compare"><i class="flaticon-refresh-square-arrows"></i></a>

                                        <a href="#" class="wishlist"><i class="fa fa-heart-o" aria-hidden="true"></i></a>

                                    </div>

                                </div>

                            </div>

                        </div>

                        <div class="product-item style1">

                            <div class="product-inner equal-elem">

                                <div class="product-thumb">

                                    <div class="thumb-inner">

                                        <a href="#"><img src="img/home4/r2.jpg" alt="r2"></a>

                                    </div>

                                    <span class="onnew">new</span>

                                    <a href="#" class="quick-view">Quick View</a>

                                </div>

                                <div class="product-innfo"> 

                                    <div class="product-name"><a href="#">Alai Smok Side Chair</a></div>

                                    <span class="price price-dark">

                                        <ins>$229.00</ins>

                                    </span>

                                    <span class="star-rating">

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <span class="review">5 Review(s)</span>

                                    </span>

                                    <div class="group-btn-hover style2">

                                        <a href="#" class="add-to-cart"><i class="fa fa-shopping-bag" aria-hidden="true"></i></a>

                                        <a href="#" class="compare"><i class="flaticon-refresh-square-arrows"></i></a>

                                        <a href="#" class="wishlist"><i class="fa fa-heart-o" aria-hidden="true"></i></a>

                                    </div>

                                </div>

                            </div>

                        </div>

                        <div class="product-item style1">

                            <div class="product-inner equal-elem">

                                <div class="product-thumb">

                                    <div class="thumb-inner">

                                        <a href="#"><img src="img/home4/r3.jpg" alt="r3"></a>

                                    </div>

                                    <a href="#" class="quick-view">Quick View</a>

                                </div>

                                <div class="product-innfo">

                                    <div class="product-name"><a href="#">Coral Springs Arm Chair</a></div>

                                    <span class="price price-dark">

                                        <ins>$229.00</ins>

                                    </span>

                                    <span class="star-rating">

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <span class="review">5 Review(s)</span>

                                    </span>

                                    <div class="group-btn-hover style2">

                                        <a href="#" class="add-to-cart"><i class="fa fa-shopping-bag" aria-hidden="true"></i></a>

                                        <a href="#" class="compare"><i class="flaticon-refresh-square-arrows"></i></a>

                                        <a href="#" class="wishlist"><i class="fa fa-heart-o" aria-hidden="true"></i></a>

                                    </div>

                                </div>

                            </div>

                        </div>

                        <div class="product-item style1">

                            <div class="product-inner equal-elem">

                                <div class="product-thumb">

                                    <div class="thumb-inner">

                                        <a href="#"><img src="img/home4/r4.jpg" alt="r4"></a>

                                    </div>

                                    <a href="#" class="quick-view">Quick View</a>

                                </div>

                                <div class="product-innfo">

                                    <div class="product-name"><a href="#">Broadway Slipcover Chair</a></div>

                                    <span class="price price-dark">

                                        <ins>$229.00</ins>

                                    </span>

                                    <span class="star-rating">

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <span class="review">5 Review(s)</span>

                                    </span>

                                    <div class="group-btn-hover style2">

                                        <a href="#" class="add-to-cart"><i class="fa fa-shopping-bag" aria-hidden="true"></i></a>

                                        <a href="#" class="compare"><i class="flaticon-refresh-square-arrows"></i></a>

                                        <a href="#" class="wishlist"><i class="fa fa-heart-o" aria-hidden="true"></i></a>

                                    </div>

                                </div>

                            </div>

                        </div>

                        <div class="product-item style1">

                            <div class="product-inner equal-elem">

                                <div class="product-thumb">

                                    <div class="thumb-inner">

                                        <a href="#"><img src="img/home4/r5.jpg" alt="r5"></a>

                                    </div>

                                    <span class="onsale">-50%</span>

                                    <a href="#" class="quick-view">Quick View</a>

                                </div>

                                <div class="product-innfo">

                                    <div class="product-name"><a href="#">Zola Licorice Dining Chair</a></div>

                                    <span class="price">

                                        <ins>$229.00</ins>

                                        <del>$259.00</del>

                                    </span>

                                    <span class="star-rating">

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <i class="fa fa-star" aria-hidden="true"></i>

                                        <span class="review">5 Review(s)</span>

                                    </span>

                                    <div class="group-btn-hover style2">

                                        <a href="#" class="add-to-cart"><i class="fa fa-shopping-bag" aria-hidden="true"></i></a>

                                        <a href="#" class="compare"><i class="flaticon-refresh-square-arrows"></i></a>

                                        <a href="#" class="wishlist"><i class="fa fa-heart-o" aria-hidden="true"></i></a>

                                    </div>

                                </div>

                            </div>

                        </div>

                        <div class="product-item style1">

                            <div class="product-inner equal-elem">

                                <div class="product-thumb">

                                    <div class="thumb-inner">

                                        <a href="#"><img src="img/home4/r6.jpg" alt="r6"></a>

                                    </div>

                                    <a href="#" class="quick-view">Quick View</a>

                                </div>

                                <div class="product-innfo">

                                    <div class="product-name"><a href="#">Chanel Volcanic Dining Chair</a></div>

                                    <span class="price price-dark">

                                        <ins>$229.00</ins>

                                    </span>

                                    <div class="group-btn-hover style2">

                                        <a href="#" class="add-to-cart"><i class="fa fa-shopping-bag" aria-hidden="true"></i></a>

                                        <a href="#" class="compare"><i class="flaticon-refresh-square-arrows"></i></a>

                                        <a href="#" class="wishlist"><i class="fa fa-heart-o" aria-hidden="true"></i></a>

                                    </div>

                                </div>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </main><!-- end MAIN -->