<!-- MAIN -->

		<main class="site-main site-login">

           

            <div class="customer-login">

                <div class="container">

                    <div class="row">

                        <div class="col-sm-6">

                            <h5 class="title-login">Log in to your account</h5>

                            <p class="p-title-login">Wellcome to your account.</p>

                            <form class="login" method="post">

                                <p class="form-row form-row-wide">

                                    <label>Username or Email Address:<span class="required"></span></label>

                                    <input type="text" value="" name="username" placeholder="Type your username or email address" class="input-text">

                                </p>

                                <p class="form-row form-row-wide">

                                    <label>Password:<span class="required"></span></label>

                                    <input type="password" name="password" placeholder="************" class="input-text">

                                </p>

                                <ul class="inline-block">

                                    <li><label class="inline" ><input type="checkbox"><span class="input"></span>Remember me</label></li>

                                </ul>

                                <a href="#" class="forgot-password" data-toggle="modal" data-target="#forgetpassword">Forgotten password?</a>


                                <p class="form-row">

                                    <input type="submit" value="Login" name="Login" class="button-submit">

                                </p>                              

                            </form>

                        </div>

                        <div class="col-sm-6 border-after">

                            <h5 class="title-login">Create an account</h5>

                            <p class="p-title-login">Fersonal infomation</p>

                            <form class="register" method="post">

                                <p class="form-row form-row-wide col-md-6 padding-left">

                                    <label>Name<span class="required">*</span></label>

                                    <input type="text" value="" name="text" placeholder="Fist name" class="input-text">

                                </p>

                                <p class="form-row form-row-wide col-md-6 padding-right">

                                    <label>Mobile No.<span class="required"></span></label>

                                    <input type="text" value="" name="text" class="input-text">

                                </p>

                                <p class="form-row form-row-wide col-md-6 padding-left">

                                    <label>Date of birth<span class="required">*</span></label>

                                    <input type="text" name="text" placeholder="Last name" class="input-text">

                                </p>

                                <p class="form-row form-row-wide col-md-6 padding-right">

                                    <label>Email Address<span class="required">*</span></label>

                                    <input type="email" name="email" placeholder="Email address" class="input-text">

                                </p>

                                <ul>

                                    <li><label class="inline" ><input type="checkbox"><span class="input"></span>Keep Me Logged In</label></li>

                                </ul>

                                

                                <p class="form-row form-row-wide col-md-6 padding-left">

                                    <label>Password:<span class="required"></span></label>

                                    <input type="password" name="password" class="input-text">

                                </p>

                                <p class="form-row form-row-wide col-md-6 padding-right">

                                    <label>Confirm Password<span class="required">*</span></label>

                                    <input type="password" name="password" class="input-text">

                                </p>
								

                                    <p style="font-size: 12px ">Password must be at least 6 characters and alphanumeric</p>

                                

                                <p class="form-row">

                                    <input type="submit" value="Submit" name="Submit" class="button-submit">

                                </p>
								<p style="font-size: 10px ">By registering, I agree to Terms & Conditions</p>

                            </form>

                        </div>

                    </div>

                </div>

            </div>

		</main><!-- end MAIN -->
		
