            <div class="header-menu-bar header-sticky" style="margin-top: 0px;"> <!---in line custom style margin--->

                <div class="header-menu-nav menu-style-2">

                    <div class="container">

                        <div class="header-menu-nav-inner">

                            <div id="box-vertical-megamenus" class="box-vertical-megamenus nav-toggle-cat">

                                <h4 class="title active">

                                    <span class="btn-open-mobile home-page">

                                        <span></span>

                                        <span></span>

                                        <span></span>

                                    </span>

                                    <span class="title-menu">All Departments</span>   

                                </h4>

                                <div class="vertical-menu-content" >
                                    <span class="btn-close hidden-md"><i class="fa fa-times" aria-hidden="true"></i></span>

                                    <ul class="vertical-menu-list">

                                        <li><a href="#">Fashion Men’s</a></li>
                                        <li class="menu-item-has-children arrow item-megamenu">

                                            <a href="#" class="dropdown-toggle">Fashion Women’s</a>

                                            <span class="toggle-submenu hidden-md"></span>

                                            <div class="submenu parent-megamenu megamenu">

                                                <div class="row">

                                                    <div class="submenu-banner submenu-banner-menu-1">

                                                        <div class="col-md-4">

                                                            <div class="dropdown-menu-info">

                                                                <h6 class="dropdown-menu-title">Fashion WoMen’s</h6>

                                                                <div class="dropdown-menu-content">

                                                                    <ul class="menu">

                                                                        <li class="menu-item"><a href="#">Leather Jackets</a></li>

                                                                        <li class="menu-item"><a href="#">Handbags</a></li>

                                                                        <li class="menu-item"><a href="#">Shoes</a></li>

                                                                        <li class="menu-item"><a href="#">Jewelrys</a></li>

                                                                        <li class="menu-item"><a href="#">Clothings</a></li>

                                                                        <li class="menu-item"><a href="#">Macbook Air</a></li>

                                                                        <li class="menu-item"><a href="#">Laptop Pro</a></li>

                                                                    </ul>

                                                                </div>

                                                            </div>

                                                        </div>

                                                        <div class="col-md-4">

                                                            <div class="dropdown-menu-info">

                                                                <h6 class="dropdown-menu-title">Accessories</h6>

                                                                <div class="dropdown-menu-content">

                                                                    <ul class="menu">

                                                                        <li class="menu-item"><a href="#">Hair Accessories</a></li>

                                                                        <li class="menu-item"><a href="#">Bloves & Mittens</a></li>

                                                                        <li class="menu-item"><a href="#">Hats</a></li>

                                                                        <li class="menu-item"><a href="#">Tech Accessories</a></li>

                                                                        <li class="menu-item"><a href="#">Head Set</a></li>

                                                                        <li class="menu-item"><a href="#">Software</a></li>

                                                                    </ul>

                                                                </div>

                                                            </div>

                                                        </div>

                                                    </div>

                                                </div>

                                            </div>

                                        </li>
                                        <li class="menu-item-has-children arrow item-megamenu">

                                            <a href="#" class="dropdown-toggle">Hand Bags</a>

                                            <span class="toggle-submenu hidden-md"></span>

                                            <div class="submenu parent-megamenu megamenu">

                                                <div class="row">

                                                    <div class="submenu-banner submenu-banner-menu-1">

                                                        <div class="col-md-4">

                                                            <div class="dropdown-menu-info">

                                                                <h6 class="dropdown-menu-title">Fashion WoMen’s</h6>

                                                                <div class="dropdown-menu-content">

                                                                    <ul class="menu">

                                                                        <li class="menu-item"><a href="#">Leather Jackets</a></li>

                                                                        <li class="menu-item"><a href="#">Handbags</a></li>

                                                                        <li class="menu-item"><a href="#">Shoes</a></li>

                                                                        <li class="menu-item"><a href="#">Jewelrys</a></li>

                                                                        <li class="menu-item"><a href="#">Clothings</a></li>

                                                                        <li class="menu-item"><a href="#">Macbook Air</a></li>

                                                                        <li class="menu-item"><a href="#">Laptop Pro</a></li>

                                                                    </ul>

                                                                </div>

                                                            </div>

                                                        </div>

                                                        <div class="col-md-4">

                                                            <div class="dropdown-menu-info">

                                                                <h6 class="dropdown-menu-title">Accessories</h6>

                                                                <div class="dropdown-menu-content">

                                                                    <ul class="menu">

                                                                        <li class="menu-item"><a href="#">Hair Accessories</a></li>

                                                                        <li class="menu-item"><a href="#">Bloves & Mittens</a></li>

                                                                        <li class="menu-item"><a href="#">Hats</a></li>

                                                                        <li class="menu-item"><a href="#">Tech Accessories</a></li>

                                                                        <li class="menu-item"><a href="#">Head Set</a></li>

                                                                        <li class="menu-item"><a href="#">Software</a></li>

                                                                    </ul>

                                                                </div>

                                                            </div>

                                                        </div>

                                                    </div>

                                                </div>

                                            </div>

                                        </li>

                                        <li><a href="#">Accessories</a>

                                        </li>

                                        <li><a href="#">Shoes</a></li>

                                        <li class="menu-item-has-children arrow item-megamenu">

                                            <a href="#" class="dropdown-toggle">Laptop & Computers</a>

                                            <span class="toggle-submenu hidden-md"></span>

                                            <div class="submenu parent-megamenu megamenu">

                                                <div class="row">

                                                    <div class="submenu-banner submenu-banner-menu-1">

                                                        <div class="col-md-4">

                                                            <div class="dropdown-menu-info">

                                                                <h6 class="dropdown-menu-title">Laptop & computers</h6>

                                                                <div class="dropdown-menu-content">

                                                                    <ul class="menu">

                                                                        <li class="menu-item"><a href="#">Laptops, Desktops & Monitors</a></li>

                                                                        <li class="menu-item"><a href="#">Printers & Ink</a></li>

                                                                        <li class="menu-item"><a href="#">Computer Accessories</a></li>

                                                                        <li class="menu-item"><a href="#">Software</a></li>

                                                                        <li class="menu-item"><a href="#">Macbook</a></li>

                                                                        <li class="menu-item"><a href="#">Macbook Air</a></li>

                                                                        <li class="menu-item"><a href="#">Laptop Pro</a></li>

                                                                    </ul>

                                                                </div>

                                                            </div>

                                                        </div>

                                                        <div class="col-md-4">

                                                            <div class="dropdown-menu-info">

                                                                <h6 class="dropdown-menu-title">Accessories</h6>

                                                                <div class="dropdown-menu-content">

                                                                    <ul class="menu">

                                                                        <li class="menu-item"><a href="#">Accessories</a></li>

                                                                        <li class="menu-item"><a href="#">Phone Batteries</a></li>

                                                                        <li class="menu-item"><a href="#">Phone Charger</a></li>

                                                                        <li class="menu-item"><a href="#">Phone Screen</a></li>

                                                                        <li class="menu-item"><a href="#">Head Set</a></li>

                                                                        <li class="menu-item"><a href="#">Software</a></li>

                                                                    </ul>

                                                                </div>

                                                            </div>

                                                        </div>

                                                    </div>

                                                </div>

                                            </div>

                                        </li>

                                        <li><a href="#">Game & Consoles</a></li>

                                        <li><a href="#">Headphone</a></li>

                                        <li><a href="#">Video Games & Consoles</a></li>

                                        <li><a href="#">Car Electronic & GDP</a></li>

                                        <li><a href="#">Virtual Reality</a></li>

                                    </ul>

                                </div>

                            </div>
                            

                            <div class="header-menu header-menu-resize">
                                
                                <ul class="header-nav krystal-nav">
                                    <li class="btn-close hidden-md"><i class="fa fa-times" aria-hidden="true"></i></li>


									<li >

                                        <a href="<?= $this->url('home'); ?>" class="dropdown-toggle">Home</a>


                                    </li>

                                    <li class="menu-item-has-children arrow">

                                        <a href="<?= $this->url('aboutus'); ?>" class="dropdown-toggle">About us</a>

                                        <span class="toggle-submenu hidden-md"></span>

                                        <ul class="submenu parent-megamenu">
										    <li class="menu-item">
                                                <a href="<?= $this->url('aboutus'); ?>" class="dropdown-toggle">About Us</a>
                                            </li>
											
                                            <li class="menu-item">
                                                 <a href="<?= $this->url('contact'); ?>" class="dropdown-toggle">Contact Us</a>
                                            </li>
											
											<li class="menu-item">
                                                <a href="<?= $this->url('blogList');?>" class="dropdown-toggle">Blog</a>
                                            </li>
											
											<li class="menu-item">
											<a href="#" class="dropdown-toggle">FAQ</a>
											</li>
											
                                            <li class="menu-item">
                                                <a href="#">How we do</a>
                                            </li>
                                            <li class="menu-item">
                                                <a href="#">Office Location</a>
                                            </li>
                                            <li class="menu-item">
                                                <a href="#">We care</a>
                                            </li>
                                        </ul>

                                    </li>

                                    <li class="menu-item-has-children arrow item-megamenu item-megamenu-sub">

                                 <!--- <a href="#" class="dropdown-toggle">Products List</a>

                                        <span class="toggle-submenu hidden-md"></span>

                                       <div class="submenu parent-megamenu megamenu">

                                            <div class="row">

                                                <div class="submenu-banner submenu-banner-menu-3">

                                                    <div class="col-md-4">

                                                        <div class="dropdown-menu-info">

                                                            <h6 class="dropdown-menu-title">Fashion Clothing</h6>

                                                            <div class="dropdown-menu-content">

                                                                <ul class="menu">

                                                                    <li class="menu-item"><a href="#">Leather Jackets</a></li>

                                                                    <li class="menu-item"><a href="#">Clothings</a></li>

                                                                    <li class="menu-item"><a href="#">shorts</a></li>

                                                                    <li class="menu-item"><a href="#">Swimwear</a></li>

                                                                    <li class="menu-item"><a href="#">Activewear</a></li>

                                                                    <li class="menu-item"><a href="#">Jacket & Coats</a></li>

                                                                </ul>

                                                            </div>

                                                        </div>

                                                    </div>

                                                    <div class="col-md-4">

                                                        <div class="dropdown-menu-info">

                                                            <h6 class="dropdown-menu-title">Handbags</h6>

                                                            <div class="dropdown-menu-content">

                                                                <ul class="menu">

                                                                    <li class="menu-item"><a href="#">Backpacks</a></li>

                                                                    <li class="menu-item"><a href="#">Travel</a></li>

                                                                    <li class="menu-item"><a href="#">Clutches</a></li>

                                                                    <li class="menu-item"><a href="#">Crossbody</a></li>

                                                                    <li class="menu-item"><a href="#">Bucket</a></li>

                                                                    <li class="menu-item"><a href="#">Wallets</a></li>

                                                                </ul>

                                                            </div>

                                                        </div>

                                                    </div>

                                                    <div class="col-md-4">

                                                        <div class="dropdown-menu-info">

                                                            <h6 class="dropdown-menu-title">Shoes</h6>

                                                            <div class="dropdown-menu-content">

                                                                <ul class="menu">

                                                                    <li class="menu-item"><a href="#">Shoes Sport</a></li>

                                                                    <li class="menu-item"><a href="#">Sneakers</a></li>

                                                                    <li class="menu-item"><a href="#">Sandals</a></li>

                                                                    <li class="menu-item"><a href="#">Booties</a></li>

                                                                    <li class="menu-item"><a href="#">Heels</a></li>

                                                                </ul>
                                                        
                                                            </div>

                                                        </div>

                                                    </div>

                                                </div>
                                                <div class="col-md-6">
                                                    <a href="#"><img src="img/home2/menu-banner-3.jpg" alt="banner3"></a>
                                                </div>
                                                <div class="col-md-6">
                                                    <a href="#"><img src="img/home2/menu-banner-4.jpg" alt="banner3"></a>
                                                </div>

                                            </div>

                                        </div> ---->
										<li><a href="<?= $this->url('login'); ?>"><i class="fa fa-user" aria-hidden="true"></i>Register / Sign in</a></li>
										<li><a href="#"><i class="fa fa-user" aria-hidden="true"></i>Log Out</a></li>

                                    </li>


                                    


                                    

                                   
                                    									

                                </ul>

                            </div>

                            <span data-action="toggle-nav" class="menu-on-mobile hidden-md">

                                <span class="btn-open-mobile home-page">

                                    <span></span>

                                    <span></span>

                                    <span></span>

                                </span>

                                <span class="title-menu-mobile">Main menu</span> 

                            </span>

                        </div>

                    </div>

                </div>

            </div>