<div class="header-content " style="margin-top: -20px;"> <!---custom style margin--->

                <div class="container">

                    <div class="row">

                        <div class="col-md-2 nav-left">

                            <!-- logo -->

                            <strong class="logo">

                                <a href="#"><img src="img/home1/logo.jpg" alt="logo"></a>

                            </strong><!-- logo -->

                        </div>

                        <div class="col-md-8 nav-mind">



                            <!-- block search -->

                            <div class="block-search" style="margin-top: 7px;"><!---custom style margin--->

                                <div class="block-content">

                                    <div class="form-search" >

                                        <form>

                                            <div class="box-group" >

                                                <input type="text" class="form-control" placeholder="Searh entire store here..." >

                                                <button class="btn btn-search" type="button"><span>search</span></button>

                                            </div>

                                        </form>

                                    </div>

                                </div>

                            </div><!-- block search -->

                        </div>
                        <div class="col-md-2 nav-right">

                            <!-- block mini cart -->

                            <div class="block-minicart dropdown">

                                

                                <a class="minicart" href="#">

                                    <span class="counter qty">

                                        <span class="cart-icon"><i class="fa fa-shopping-bag" aria-hidden="true"></i></span>

                                        <span class="counter-number">2</span>

                                    </span>

                                    <span class="counter-your-cart">

                                       <!-- <span class="counter-label">Your Cart:</span>

                                            <span class="counter-price">$00.00</span> --->

                                    </span>

                                </a>

                                <div class="parent-megamenu">

                                    <form>

                                        <div class="minicart-content-wrapper" >

                                            <div class="subtitle">

                                                You have <span>2</span> item(s) in your cart

                                            </div>

                                            <div class="minicart-items-wrapper">

                                                <ol class="minicart-items">

                                                    <li class="product-inner">

                                                        <div class="product-thumb style1">

                                                            <div class="thumb-inner">

                                                                <a href="#"><img src="img/home1/c1.jpg" alt="c1"></a>

                                                            </div>

                                                        </div>

                                                        <div class="product-innfo">

                                                            <div class="product-name"><a href="#">Xbox One S Halo Collection Bund</a></div>

                                                            <a href="#" class="remove"><i class="fa fa-times" aria-hidden="true"></i></a>

                                                            <span class="price price-dark">

                                                                <ins>$229.00</ins>

                                                            </span>

                                                        </div>

                                                    </li>

                                                    <li class="product-inner">

                                                        <div class="product-thumb style1">

                                                            <div class="thumb-inner">

                                                                <a href="#"><img src="img/home1/c2.jpg" alt="c2"></a>

                                                            </div>

                                                        </div>

                                                        <div class="product-innfo">

                                                            <div class="product-name"><a href="#">Acer's Aspire S7 is a thin and portable...</a></div>
                                                            <a href="#" class="remove"><i class="fa fa-times" aria-hidden="true"></i></a>

                                                            <span class="price">

                                                                <ins>$229.00</ins>

                                                                <del>$259.00</del>

                                                            </span>

                                                        </div>

                                                    </li>

                                                </ol>

                                            </div>

                                            <div class="subtotal">

                                                <span class="label">Total :</span>

                                                <span class="price">$480.00</span>

                                            </div>

                                            <div class="actions">

                                                <a class="btn btn-viewcart" href="<?= $this->url('viewcart'); ?>">View cart</a><!------ shoppingcart is a name of phtml file which is available in Application/view/application/shopping-cart folder-->

                                                <a class="btn btn-checkout" href="<?= $this->url('checkout'); ?>">Checkout</a>

                                            </div>

                                        </div>

                                    </form>

                                </div>

                            </div><!-- block mini cart -->

                            <a href="#" class="hidden-md search-hidden"><span class="pe-7s-search"></span></a>

                            <a class="wishlist-minicart" href="<?= $this->url('wishlist'); ?>"><i class="fa fa-heart-o" aria-hidden="true"></i></a>

                        </div>

                    </div>

                </div>

            </div>