
                <div class="footer-column equal-container">

                    <div class="container">

                        <div class="row">

                            <div class="col-md-4 col-sm-6 equal-elem">

                                <h3 class="title-of-section">About Us</h3>

                                <div class="contacts">

                                    <p class="contacts-info">Nullam tristique tortor nibh, in viverra libero sollicitudin ac. Suspendisse quis lacinia ipsum. Etiam scelerisque sit amet lectus quis lacinia. Sed condimentum auctor.</p>

                                    <span class="contacts-info info-address ">218 Fifth Avenue, HeavenTower NewYork City</span>

                                    <span class="contacts-info info-phone">(+68) 123 456 7890</span>

                                    <span class="contacts-info info-support">Hot-Support@Krystal.com</span>

                                    <div class="socials">

                                        <a href="#" class="social"><i class="fa fa-twitter" aria-hidden="true"></i></a>

                                        <a href="#" class="social"><i class="fa fa-facebook" aria-hidden="true"></i></a>

                                        <a href="#" class="social"><i class="fa fa-pinterest" aria-hidden="true"></i></a>

                                        <a href="#" class="social"><i class="fa fa-instagram" aria-hidden="true"></i></a>

                                        <a href="#" class="social"><i class="fa fa-vimeo" aria-hidden="true"></i></a>

                                        <a href="#" class="social"><i class="fa fa-youtube" aria-hidden="true"></i></a>

                                    </div>

                                </div>

                            </div>

                            <div class="col-md-2 col-sm-6 equal-elem">

                                <div class="links">

                                <h3 class="title-of-section">My account</h3>

                                <ul>

                                    <li><a href="#">Sign In</a></li>

                                    <li><a href="#">View Cart</a></li>

                                    <li><a href="#">My Wishlist</a></li>

                                    <li><a href="#">Terms & Conditions</a></li>

                                    <li><a href="#">Contact us</a></li>

                                    <li><a href="#">Track My Order</a></li>

                                    <li><a href="#">Help</a></li>

                                </ul>

                                </div>

                            </div>

                            <div class="col-md-2 col-sm-6 equal-elem">

                                <div class="links">

                                <h3 class="title-of-section">Information</h3>

                                <ul>

                                    <li><a href="#">Specials</a></li>

                                    <li><a href="#">New products</a></li>

                                    <li><a href="#">Best sellers</a></li>

                                    <li><a href="#">Our stores</a></li>

                                    <li><a href="#">Contact us</a></li>

                                    <li><a href="#">Sitemap</a></li>

                                    <li><a href="#">Blog</a></li>

                                </ul>

                                </div>

                            </div>

                            <div class="col-md-4 col-sm-6 equal-elem">

                                <div class="links links-ins">

                                    <h3 class="title-of-section">Instagram</h3>

                                    <div class="content-ins">

                                        <a href="#"><img src="img/detail/ins1.jpg" alt="ins1"></a>

                                        <a href="#"><img src="img/detail/ins2.jpg" alt="ins2"></a>

                                        <a href="#"><img src="img/detail/ins3.jpg" alt="ins3"></a>

                                        <a href="#"><img src="img/detail/ins4.jpg" alt="ins4"></a>

                                        <a href="#"><img src="img/detail/ins5.jpg" alt="ins5"></a>

                                        <a href="#"><img src="img/detail/ins6.jpg" alt="ins6"></a>

                                        <a href="#"><img src="img/detail/ins7.jpg" alt="ins7"></a>

                                        <a href="#"><img src="img/detail/ins8.jpg" alt="ins8"></a>

                                        <a href="#"><img src="img/detail/ins9.jpg" alt="ins9"></a>

                                        <a href="#"><img src="img/detail/ins10.jpg" alt="ins10"></a>

                                    </div>

                                    <a href="#" class="view-more">View More<!-- <i class="fa fa-arrow-circle-right" aria-hidden="true"></i> --></a>

                                </div>

                            </div>

                        </div>

                    </div>

                </div>