
            <div class="header-menu-bar header-sticky">

                <div class="header-menu-nav menu-style-2">

                    <div class="container">

                        <div class="header-menu-nav-inner">

                            <div id="box-vertical-megamenus" class="box-vertical-megamenus nav-toggle-cat">

                                <h4 class="title active">

                                    <span class="btn-open-mobile home-page">

                                        <span></span>

                                        <span></span>

                                        <span></span>

                                    </span>

                                    <span class="title-menu">All Departments</span>   

                                </h4>

                                <div class="vertical-menu-content" >
                                    <span class="btn-close hidden-md"><i class="fa fa-times" aria-hidden="true"></i></span>

                                    <ul class="vertical-menu-list">

                                        <li><a href="#">Fashion Men’s</a></li>
                                        <li class="menu-item-has-children arrow item-megamenu">

                                            <a href="#" class="dropdown-toggle">Fashion Women’s</a>

                                            <span class="toggle-submenu hidden-md"></span>

                                            <div class="submenu parent-megamenu megamenu">

                                                <div class="row">

                                                    <div class="submenu-banner submenu-banner-menu-1">

                                                        <div class="col-md-4">

                                                            <div class="dropdown-menu-info">

                                                                <h6 class="dropdown-menu-title">Fashion WoMen’s</h6>

                                                                <div class="dropdown-menu-content">

                                                                    <ul class="menu">

                                                                        <li class="menu-item"><a href="#">Leather Jackets</a></li>

                                                                        <li class="menu-item"><a href="#">Handbags</a></li>

                                                                        <li class="menu-item"><a href="#">Shoes</a></li>

                                                                        <li class="menu-item"><a href="#">Jewelrys</a></li>

                                                                        <li class="menu-item"><a href="#">Clothings</a></li>

                                                                        <li class="menu-item"><a href="#">Macbook Air</a></li>

                                                                        <li class="menu-item"><a href="#">Laptop Pro</a></li>

                                                                    </ul>

                                                                </div>

                                                            </div>

                                                        </div>

                                                        <div class="col-md-4">

                                                            <div class="dropdown-menu-info">

                                                                <h6 class="dropdown-menu-title">Accessories</h6>

                                                                <div class="dropdown-menu-content">

                                                                    <ul class="menu">

                                                                        <li class="menu-item"><a href="#">Hair Accessories</a></li>

                                                                        <li class="menu-item"><a href="#">Bloves & Mittens</a></li>

                                                                        <li class="menu-item"><a href="#">Hats</a></li>

                                                                        <li class="menu-item"><a href="#">Tech Accessories</a></li>

                                                                        <li class="menu-item"><a href="#">Head Set</a></li>

                                                                        <li class="menu-item"><a href="#">Software</a></li>

                                                                    </ul>

                                                                </div>

                                                            </div>

                                                        </div>

                                                    </div>

                                                </div>

                                            </div>

                                        </li>
                                        <li class="menu-item-has-children arrow item-megamenu">

                                            <a href="#" class="dropdown-toggle">Hand Bags</a>

                                            <span class="toggle-submenu hidden-md"></span>

                                            <div class="submenu parent-megamenu megamenu">

                                                <div class="row">

                                                    <div class="submenu-banner submenu-banner-menu-1">

                                                        <div class="col-md-4">

                                                            <div class="dropdown-menu-info">

                                                                <h6 class="dropdown-menu-title">Fashion WoMen’s</h6>

                                                                <div class="dropdown-menu-content">

                                                                    <ul class="menu">

                                                                        <li class="menu-item"><a href="#">Leather Jackets</a></li>

                                                                        <li class="menu-item"><a href="#">Handbags</a></li>

                                                                        <li class="menu-item"><a href="#">Shoes</a></li>

                                                                        <li class="menu-item"><a href="#">Jewelrys</a></li>

                                                                        <li class="menu-item"><a href="#">Clothings</a></li>

                                                                        <li class="menu-item"><a href="#">Macbook Air</a></li>

                                                                        <li class="menu-item"><a href="#">Laptop Pro</a></li>

                                                                    </ul>

                                                                </div>

                                                            </div>

                                                        </div>

                                                        <div class="col-md-4">

                                                            <div class="dropdown-menu-info">

                                                                <h6 class="dropdown-menu-title">Accessories</h6>

                                                                <div class="dropdown-menu-content">

                                                                    <ul class="menu">

                                                                        <li class="menu-item"><a href="#">Hair Accessories</a></li>

                                                                        <li class="menu-item"><a href="#">Bloves & Mittens</a></li>

                                                                        <li class="menu-item"><a href="#">Hats</a></li>

                                                                        <li class="menu-item"><a href="#">Tech Accessories</a></li>

                                                                        <li class="menu-item"><a href="#">Head Set</a></li>

                                                                        <li class="menu-item"><a href="#">Software</a></li>

                                                                    </ul>

                                                                </div>

                                                            </div>

                                                        </div>

                                                    </div>

                                                </div>

                                            </div>

                                        </li>

                                        <li><a href="#">Accessories</a>

                                        </li>

                                        <li><a href="#">Shoes</a></li>

                                        <li class="menu-item-has-children arrow item-megamenu">

                                            <a href="#" class="dropdown-toggle">Laptop & Computers</a>

                                            <span class="toggle-submenu hidden-md"></span>

                                            <div class="submenu parent-megamenu megamenu">

                                                <div class="row">

                                                    <div class="submenu-banner submenu-banner-menu-1">

                                                        <div class="col-md-4">

                                                            <div class="dropdown-menu-info">

                                                                <h6 class="dropdown-menu-title">Laptop & computers</h6>

                                                                <div class="dropdown-menu-content">

                                                                    <ul class="menu">

                                                                        <li class="menu-item"><a href="#">Laptops, Desktops & Monitors</a></li>

                                                                        <li class="menu-item"><a href="#">Printers & Ink</a></li>

                                                                        <li class="menu-item"><a href="#">Computer Accessories</a></li>

                                                                        <li class="menu-item"><a href="#">Software</a></li>

                                                                        <li class="menu-item"><a href="#">Macbook</a></li>

                                                                        <li class="menu-item"><a href="#">Macbook Air</a></li>

                                                                        <li class="menu-item"><a href="#">Laptop Pro</a></li>

                                                                    </ul>

                                                                </div>

                                                            </div>

                                                        </div>

                                                        <div class="col-md-4">

                                                            <div class="dropdown-menu-info">

                                                                <h6 class="dropdown-menu-title">Accessories</h6>

                                                                <div class="dropdown-menu-content">

                                                                    <ul class="menu">

                                                                        <li class="menu-item"><a href="#">Accessories</a></li>

                                                                        <li class="menu-item"><a href="#">Phone Batteries</a></li>

                                                                        <li class="menu-item"><a href="#">Phone Charger</a></li>

                                                                        <li class="menu-item"><a href="#">Phone Screen</a></li>

                                                                        <li class="menu-item"><a href="#">Head Set</a></li>

                                                                        <li class="menu-item"><a href="#">Software</a></li>

                                                                    </ul>

                                                                </div>

                                                            </div>

                                                        </div>

                                                    </div>

                                                </div>

                                            </div>

                                        </li>

                                        <li><a href="#">Game & Consoles</a></li>

                                        <li><a href="#">Headphone</a></li>

                                        <li><a href="#">Video Games & Consoles</a></li>

                                        <li><a href="#">Car Electronic & GDP</a></li>

                                        <li><a href="#">Virtual Reality</a></li>

                                    </ul>

                                </div>

                            </div>
                            

                            <div class="header-menu header-menu-resize">
                                
                                <ul class="header-nav krystal-nav">
                                    <li class="btn-close hidden-md"><i class="fa fa-times" aria-hidden="true"></i></li>

                                    <li class="menu-item-has-children arrow">

                                        <a href="index2.html" class="dropdown-toggle">Home</a>

                                        <span class="toggle-submenu hidden-md"></span>
                                        <ul class="submenu parent-megamenu">
                                            <li class="menu-item">
                                                <a href="index.html">Home 1</a>
                                            </li>
                                            <li class="menu-item">
                                                <a href="index2.html">Home 2</a>
                                            </li>
                                            <li class="menu-item">
                                                <a href="index3.html">Home 3</a>
                                            </li>
                                            <li class="menu-item">
                                                <a href="index4.html">Home 4</a>
                                            </li>
                                            <li class="menu-item">
                                                <a href="index5.html">Home 5</a>
                                            </li>
                                        </ul>

                                    </li>

                                    <li class="menu-item-has-children arrow">

                                        <a href="#" class="dropdown-toggle">Demos</a>

                                        <span class="toggle-submenu hidden-md"></span>

                                        <ul class="submenu parent-megamenu">
                                            <li class="menu-item">
                                                <a href="grid-product.html">Grid Product</a>
                                            </li>
                                            <li class="menu-item">
                                                <a href="list-product.html">List Product</a>
                                            </li>
                                            <li class="menu-item">
                                                <a href="list-product-right.html">List Product Right</a>
                                            </li>
                                            <li class="menu-item">
                                                <a href="grid-product-right.html">Grid Product Right</a>
                                            </li>
                                            <li class="menu-item">
                                                <a href="detail.html">Detail Product</a>
                                            </li>
                                        </ul>

                                    </li>

                                    <li class="menu-item-has-children arrow item-megamenu item-megamenu-sub">

                                        <a href="#" class="dropdown-toggle">Fashions</a>

                                        <span class="toggle-submenu hidden-md"></span>

                                        <div class="submenu parent-megamenu megamenu">

                                            <div class="row">

                                                <div class="submenu-banner submenu-banner-menu-3">

                                                    <div class="col-md-4">

                                                        <div class="dropdown-menu-info">

                                                            <h6 class="dropdown-menu-title">Fashion Clothing</h6>

                                                            <div class="dropdown-menu-content">

                                                                <ul class="menu">

                                                                    <li class="menu-item"><a href="#">Leather Jackets</a></li>

                                                                    <li class="menu-item"><a href="#">Clothings</a></li>

                                                                    <li class="menu-item"><a href="#">shorts</a></li>

                                                                    <li class="menu-item"><a href="#">Swimwear</a></li>

                                                                    <li class="menu-item"><a href="#">Activewear</a></li>

                                                                    <li class="menu-item"><a href="#">Jacket & Coats</a></li>

                                                                </ul>

                                                            </div>

                                                        </div>

                                                    </div>

                                                    <div class="col-md-4">

                                                        <div class="dropdown-menu-info">

                                                            <h6 class="dropdown-menu-title">Handbags</h6>

                                                            <div class="dropdown-menu-content">

                                                                <ul class="menu">

                                                                    <li class="menu-item"><a href="#">Backpacks</a></li>

                                                                    <li class="menu-item"><a href="#">Travel</a></li>

                                                                    <li class="menu-item"><a href="#">Clutches</a></li>

                                                                    <li class="menu-item"><a href="#">Crossbody</a></li>

                                                                    <li class="menu-item"><a href="#">Bucket</a></li>

                                                                    <li class="menu-item"><a href="#">Wallets</a></li>

                                                                </ul>

                                                            </div>

                                                        </div>

                                                    </div>

                                                    <div class="col-md-4">

                                                        <div class="dropdown-menu-info">

                                                            <h6 class="dropdown-menu-title">Shoes</h6>

                                                            <div class="dropdown-menu-content">

                                                                <ul class="menu">

                                                                    <li class="menu-item"><a href="#">Shoes Sport</a></li>

                                                                    <li class="menu-item"><a href="#">Sneakers</a></li>

                                                                    <li class="menu-item"><a href="#">Sandals</a></li>

                                                                    <li class="menu-item"><a href="#">Booties</a></li>

                                                                    <li class="menu-item"><a href="#">Heels</a></li>

                                                                </ul>
                                                        
                                                            </div>

                                                        </div>

                                                    </div>

                                                </div>
                                                <div class="col-md-6">
                                                    <a href="#"><img src="img/home2/menu-banner-3.jpg" alt="banner3"></a>
                                                </div>
                                                <div class="col-md-6">
                                                    <a href="#"><img src="img/home2/menu-banner-4.jpg" alt="banner3"></a>
                                                </div>

                                            </div>

                                        </div>

                                    </li>

                                    <li class="menu-item-has-children arrow">

                                        <a href="#" class="dropdown-toggle">Sub Menu</a>

                                        <span class="toggle-submenu hidden-md"></span>

                                        <ul class="submenu parent-megamenu">
                                            <li class="menu-item">
                                                <a href="checkout.html">Checkout</a>
                                            </li>
                                            <li class="menu-item">
                                                <a href="shopping-cart.html">Shopping Cart</a>
                                            </li>
                                            <li class="menu-item">
                                                <a href="contact-us.html">Contact Us</a>
                                            </li>
                                            <li class="menu-item">
                                                <a href="login.html">Login</a>
                                            </li>
                                        </ul>

                                    </li>

                                    <li>

                                        <a href="contact-us.html" class="dropdown-toggle">Contact Us</a>

                                        <span class="toggle-submenu hidden-md"></span>

                                    </li>

                                    <li class="menu-item-has-children arrow">

                                        <a href="#" class="dropdown-toggle">Blog</a>

                                        <span class="toggle-submenu hidden-md"></span>

                                        <ul class="submenu parent-megamenu">
                                            <li class="menu-item">
                                                <a href="blog-grid.html">Blog Grid</a>
                                            </li>
                                            <li class="menu-item">
                                                <a href="blog-list.html">Blog List</a>
                                            </li>
                                            <li class="menu-item">
                                                <a href="blog-single.html">Blog Single</a>
                                            </li>
                                        </ul>

                                    </li>

                                </ul>

                            </div>

                            <span data-action="toggle-nav" class="menu-on-mobile hidden-md">

                                <span class="btn-open-mobile home-page">

                                    <span></span>

                                    <span></span>

                                    <span></span>

                                </span>

                                <span class="title-menu-mobile">Main menu</span> 

                            </span>

                        </div>

                    </div>

                </div>

            </div>